language: cpp
matrix:
  include:
    - os: linux
      compiler: clang
      name: clang-ninja
      sudo: required
      env: TASK=clang
      dist: xenial
      cache:
        ccache: true
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - ninja-build
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
      script: 
        - ./travis.sh
      deploy:
        - provider: releases
          api_key: "$GH_TOKEN"
          overwrite: true
          file: "crossuo-linux-master.tgz"
          skip_cleanup: true
          tag_name: master
          on:
            tags: false
            branch: master
            repo: crossuo/crossuo
        - provider: releases
          api_key: "$GH_TOKEN"
          overwrite: true
          file: "crossuo-linux-v$TRAVIS_TAG.tgz"
          skip_cleanup: true
          on:
            tags: true
            repo: crossuo/crossuo
      install:
        - |
          CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.5-Linux-x86_64.tar.gz"
          mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=${PWD}/cmake/bin:${PATH}
        - cmake --version
    - os: linux
      on:
        repo: crossuo/crossuo
      compiler: gcc
      name: gcc-make
      sudo: required
      env: TASK=gcc
      dist: xenial
      cache:
        ccache: true
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
            - g++-7
            - gcc-7
      script: ./travis.sh
      install:
        - |
          CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.5-Linux-x86_64.tar.gz"
          mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=${PWD}/cmake/bin:${PATH}
        - cmake --version
    - os: linux
      name: format-check
      sudo: required
      env: TASK=clang-format
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-format-7
      script:
        - ./travis.sh
    - os: osx
      sudo: false
      addons:
        homebrew:
          packages:
            - ccache
            - ninja
      install:
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      osx_image: xcode10
      cache:
        ccache: true
      script:
        - ./travis.sh
      deploy:
        - provider: releases
          api_key: "$GH_TOKEN"
          overwrite: true
          file: "crossuo-osx-master.zip"
          skip_cleanup: true
          tag_name: master
          on:
            tags: false
            branch: master
            repo: crossuo/crossuo
        - provider: releases
          api_key: "$GH_TOKEN"
          overwrite: true
          file: "crossuo-osx-v$TRAVIS_TAG.zip"
          skip_cleanup: true
          on:
            tags: true
            repo: crossuo/crossuo
