language: cpp
branches:
  only:
    - master
    - /v\d+\.*/
matrix:
  include:
    - os: linux
      compiler: clang
      name: clang-ninja
      sudo: required
      env: TASK=clang
      dist: xenial
      cache:
        ccache: true
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - ninja-build
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
      script: 
        - ./travis.sh
      before_deploy:
        - git tag nightly -f
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        overwrite: true
        file: "crossuo-linux-nightly.tgz"
        skip_cleanup: true
        on:
          tags: false
          all_branches: true
          repo: crossuo/crossuo
      install:
        - |
          CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.5-Linux-x86_64.tar.gz"
          mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=${PWD}/cmake/bin:${PATH}
        - cmake --version
    - os: linux
      compiler: gcc
      name: gcc-make
      sudo: required
      env: TASK=gcc
      dist: xenial
      cache:
        ccache: true
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - libglu1-mesa-dev
            - libegl1-mesa-dev
            - libgles2-mesa-dev
            - xorg-dev
            - libsdl2-dev
            - libglew-dev
            - libsndio-dev
            - libxkbcommon-dev
            - g++-7
            - gcc-7
      script: ./travis.sh
      install:
        - |
          CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.5-Linux-x86_64.tar.gz"
          mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
          export PATH=${PWD}/cmake/bin:${PATH}
        - cmake --version
    - os: linux
      name: format-check
      sudo: required
      env: TASK=clang-format
      dist: xenial
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
          packages:
            - clang-format-7
      script: 
        - ./travis.sh
    - os: osx
      sudo: false
      addons:
        homebrew:
          packages:
            - ccache
            - ninja
      #      - sdl2
      #      - glew
      #      - gcc@6
      #    update: true
      install:
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      osx_image: xcode10
      #before_cache:
      #  - brew cleanup
      cache: 
        ccache: true
        directories:
      #    - $HOME/Library/Caches/Homebrew
      script:
        - ./travis.sh
      before_deploy:
        - git tag nightly -f
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        overwrite: true
        tag_name: nightly
        file: "crossuo-osx-nightly.zip"
        skip_cleanup: true
        on:
          tags: false
          all_branches: true
          repo: crossuo/crossuo
